### ISSUE TITLE
Check if tree and curl is installed

### ISSUE THREAD

**Issue by koksnuss** [theno/fabsetup#2]
When creating a new addon with `fabsetup new_addon` it seems to use `tree` and also `curl` which is not installed by default on many OS.

The easiest fix for this I can think of would be to pull it in as a dependency while installing it via `pip`. However I dont know if this is even possible. Otherwise it should at least been tested before the default operation of `fabsetup`.

**Comment by theno** [comment]
This hint affects to fabsetup < 1.0.0, i close it now.
